### ISSUE TITLE
Selected apps TProxy-fication

### ISSUE THREAD

**Issue by Anderhar** [XTLS/Xray-docs-next#492]
Currently, the documentation provides as many as three tutorials ([1](https://xtls.github.io/en/document/level-2/transparent_proxy/transparent_proxy.html),[2](https://xtls.github.io/en/document/level-2/tproxy_ipv4_and_ipv6.html),[3](https://xtls.github.io/Xray-docs-next/en/document/level-2/iptables_gid.html#_4-setting-up-iptables-rules)) on how to set up a TProxy using IPTables, but all of them assume redirecting all system traffic, which is redundant for cases where only one app needs to be proxied, in particular some VPN client on Android. The latter is a fairly demanded task among users, but not among developers for some reason. Would it be possible to request an additional tutorial on how to redirect only selected apps to TProxy via IPTables? I think it would be in demand.

**Comment by Fangliding** [comment]
The working mechanics of VPN clients on Android are completely different from TProxy

**Comment by Fangliding** [comment]
> > The working mechanics of VPN clients on Android are completely different from TProxy
> 
> I mean tunnel-in-tunnel, like a chains in NekoBox, but for entire applications. Unblock restricted VPN apps by tunneling to Xray's TProxy via IPTables seems to be the best solution in terms of performance and reliability. But this applies to any other android apps without SOCKS/HTTP proxy support when occupying the system TUN is unwelcome.

Do you know that operating iptables on Android requires root access? How many people meet this condition?
Incorrect configuration of iptables on Android may cause the device unable to boot. I never recommend ordinary users to do this
If you have enough confidence in your abilities, you can try to configure them yourself.

**Comment by Fangliding** [comment]
@Anderhar 
> Root access is not a problem for users, but only for developers again, which is why there's no GUI for Xray/V2Ray/Sing-Box that provides root capabilities despite requests.

I cannot understand this sentence "not a problem for users, but only for developers" what?

>It is very sad that you rushed to close the issue without proper analysis. Already having three nearly identical guides on TProxy+IPTables in Xray wiki, it is very strange to see a request for another one get denied.

It is reasonable to use tproxy on Linux PC as it already has a considerable user base
You proposed an idea and entered a new field, no tutorial to be found is very very normal.
If your request does meet the needs of many people, we will consider it, but because of your individual needs, we need to spend time writing a complete tutorial. Why?
You want to improve proxy efficiency on Android, yes, no problem, but please learn how to do it yourself. Perhaps one day, you can bring your knowledge back to solve other people's problems or even write a guide. But it's not right to just cry like a baby and wait for parents to feed food into his mouth
